language: r
sudo: false
dist: trusty
group: deprecated-2017Q4

r:
  - oldrel
  - release
  - devel

cache: packages

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("pkg")'
script:
  - Rscript -e 'devtools::check("pkg")'

notifications:
  email:
    on_success: change
    on_failure: change
